CREATE USER SCRAM WITH ENCRYPTED PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE POSTGRES TO SCRAM;

CREATE USER SOCKET WITH ENCRYPTED PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE POSTGRES TO SOCKET;
