CREATE USER MD5 WITH PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE POSTGRES TO MD5;

CREATE USER CLEAR WITH PASSWORD 'postgres'; 
GRANT ALL PRIVILEGES ON DATABASE POSTGRES TO CLEAR;

ALTER SYSTEM SET password_encryption = 'scram-sha-256';
SELECT pg_reload_conf();
CREATE USER SCRAM WITH PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE POSTGRES TO SCRAM;
