CREATE USER MD5 WITH PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE POSTGRES TO MD5;

CREATE USER CLEAR WITH PASSWORD 'postgres'; 
GRANT ALL PRIVILEGES ON DATABASE POSTGRES TO CLEAR;

CREATE USER SCRAM WITH PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE POSTGRES TO SCRAM;
